### ISSUE TITLE
Create additional templates for the sign up process

### ISSUE THREAD

**Issue by victor-nitu** [thesponge/kep#3]
We need some more templates for:
- [x] sign up
- [x] a partial for 3rd party OAuth providers
- [x] password recovery
- [x] account confirmation

**Comment by nightsh** [comment]
Also, after signing up via OAuth, there's an additional step for providing a (or changing the imported) screen name and email address. Those need templates too.

**Comment by victor-nitu** [comment]
password recovery is almost here, too.
